version: 2

changelog:
  use: github-native
  sort: asc

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -buildmode=pie
      - -buildvcs=true
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X main.version={{ if .IsSnapshot }}devel{{ else }}{{ .Tag }}{{ end }}'

archives:
  - id: binary-archive
    name_template: "{{ .ProjectName }}"
    formats: binary
  - id: tar-archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: tar.gz
    # hack to only add binary to archive
    files:
      - none*

checksum:
  name_template: "checksums.txt"
  ids:
    - binary-archive
    - tar-archive

signs:
  - id: checksum-signature
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

release:
  ids:
    - checksum-signature
    - tar-archive
  prerelease: auto
  name_template: "{{ .Tag }}"
