project_name: goreleaser-test

env:
  - COSIGN_EXPERIMENTAL=true

changelog:
  use: github
  sort: asc

gomod:
  proxy: true

builds:
  - binary: goreleaser-test
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -buildmode=pie
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X "main.version={{ .Tag }}"

sboms:
  - artifacts: binary

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

signs:
  - cmd: cosign
    certificate: "${artifact}.crt"
    args: ["sign-blob", "--output-signature", "${signature}", "--output-certificate", "${certificate}", "${artifact}"]
    artifacts: all

release:
  prerelease: auto
  name_template: "Release {{ .Tag }}"
