name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GO_VERSION: "1.19"

jobs:
  check-mod-tidy:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}.x
          check-latest: true
          cache: true

      - run: |
          go mod tidy -compat ${{ env.GO_VERSION }}
          STATUS=$( git status --porcelain go.mod go.sum )
          if [ ! -z "$STATUS" ]; then
              echo "Running go mod tidy modified go.mod and/or go.sum"
              exit 1
          fi
          exit 0

  staticcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}.x
          check-latest: true
          cache: true

      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          install-go: false

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}.x
          check-latest: true
          cache: true

      - uses: golangci/golangci-lint-action@v3.3.0
        with:
          only-new-issues: true
