name: Lint Dockerfile

on:
  push:
    paths:
      - Dockerfile

  workflow_dispatch: {}

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          no-color: true
          verbose: true
