name: Release

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

env:
  GO_VERSION: "1.19"

jobs:
  release-binary:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tag')
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}.x
          check-latest: true
          cache: true

      - uses: sigstore/cosign-installer@main

      - uses: goreleaser/goreleaser-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          version: latest
          args: release

      - run: |
          REPO="${{ github.repository }}"
          REPO_NAME="${REPO#*/}"
          cp "dist/${REPO_NAME}_linux_amd64_v1/${REPO_NAME}" released-binary

      - uses: actions/upload-artifact@v3
        with:
          name: released-binary
          path: ./released-binary

  reproduce-binary:
    runs-on: ubuntu-latest
    needs: release-binary
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}.x
          check-latest: true
          cache: true

      - uses: actions/download-artifact@v3
        with:
          name: released-binary

      - run: |
          go install github.com/capnspacehook/gorepro@latest
          gorepro -b=-buildmode=pie -no-go-gc released-binary

  release-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: sigstore/cosign-installer@main

      - uses: docker/setup-buildx-action@v2

      - id: tag-types
        run: |
          if [[ ${{ contains(github.ref, 'tag') }} == true ]]; then
            TAGS="
            type=semver,pattern={{major}},priority=920
            type=semver,pattern={{major}}.{{minor}},priority=910
            type=semver,pattern={{version}},priority=900
            type=ref,event=branch
            type=sha,format=long"
          else
            TAGS="
            type=ref,event=branch
            type=sha,format=long"
          fi

          # https://trstringer.com/github-actions-multiline-strings
          echo "TAGS<<EOF" >> $GITHUB_ENV
          echo "$TAGS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: ${{ env.TAGS }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: get-tag
        uses: olegtarasov/get-tag@v2.1

      - id: build-push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            VERSION=${{ steps.get-tag.outputs.tag }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ghcr.io/${{ github.repository }}@${{ steps.build-push.outputs.digest }}

      - uses: chainguard-images/actions/vul-scans@main
        with:
          image: ghcr.io/${{ github.repository }}@${{ steps.build-push.outputs.digest }}
          RUN_SNYK: false
