name: Release

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  release-binaries:
    permissions:
      contents: write
      id-token: write
    uses: capnspacehook/go-workflows/.github/workflows/release-binaries.yml@master

  release-image:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: capnspacehook/go-workflows/.github/workflows/release-image.yml@master
