name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

  workflow_dispatch: {}

jobs:
  test:
    permissions:
      contents: read
    uses: capnspacehook/go-workflows/.github/workflows/test.yml@master
