name: Vulnerability scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

  workflow_dispatch: {}

env:
  GO_VERSION: "1.19"

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}.x
          check-latest: true
          cache: true

      - name: Scan for known vulnerable dependencies
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck -v ./...
